apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n01743943-nginx-app
  namespace: argocd
  labels:
    student-id: n01743943
spec:
  project: default
  
  source:
    repoURL: https://github.com/Diwakarsaini7/n01743943_CCGC5504_FINAL_EXAM.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
        
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      
  revisionHistoryLimit: 10