apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment
  namespace: nginx-app
  labels:
    app: nginx-app
    student-id: n01743943
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
        student-id: n01743943
    spec:
      containers:
      - name: nginx-app
        image: diwakar1002/n01743943-nginx-app:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5