apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: nginx-app
  labels:
    app: nginx-app
    student-id: n01743943
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: nginx-app